/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskQueueIndexRouteImport } from './routes/task-queue/index'
import { Route as CommunityPostsIndexRouteImport } from './routes/community-posts/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskQueueIndexRoute = TaskQueueIndexRouteImport.update({
  id: '/task-queue/',
  path: '/task-queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPostsIndexRoute = CommunityPostsIndexRouteImport.update({
  id: '/community-posts/',
  path: '/community-posts/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community-posts/': typeof CommunityPostsIndexRoute
  '/task-queue/': typeof TaskQueueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community-posts': typeof CommunityPostsIndexRoute
  '/task-queue': typeof TaskQueueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community-posts/': typeof CommunityPostsIndexRoute
  '/task-queue/': typeof TaskQueueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/community-posts/' | '/task-queue/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/community-posts' | '/task-queue'
  id: '__root__' | '/' | '/community-posts/' | '/task-queue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityPostsIndexRoute: typeof CommunityPostsIndexRoute
  TaskQueueIndexRoute: typeof TaskQueueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-queue/': {
      id: '/task-queue/'
      path: '/task-queue'
      fullPath: '/task-queue/'
      preLoaderRoute: typeof TaskQueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-posts/': {
      id: '/community-posts/'
      path: '/community-posts'
      fullPath: '/community-posts/'
      preLoaderRoute: typeof CommunityPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityPostsIndexRoute: CommunityPostsIndexRoute,
  TaskQueueIndexRoute: TaskQueueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
